name: Auto-Build ARM Binary

on: [push] 

permissions:
  contents: write 

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ARM binary using QEMU emulator
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          run: |
            # 1. Install build dependencies (remove libraylib-dev)
            apt-get update
            apt-get install -y build-essential libx11-dev libgl1-mesa-dev libssl-dev libncurses5-dev libncursesw5-dev nlohmann-json3-dev cmake git

            # 2. Build Raylib from source
            git clone https://github.com/raysan5/raylib.git
            cd raylib/src
            make -j$(nproc)
            make install
            cd ../..

            # 3. Build Replxx for ARM from source
            git clone https://github.com/AmokHuginnsson/replxx.git
            cd replxx
            mkdir build && cd build
            cmake .. -DBUILD_SHARED_LIBS=OFF -DREPLXX_BUILD_EXAMPLES=OFF
            make -j$(nproc)
            make install
            cd ../..

            # 4. Create the builds directory
            mkdir -p builds

            # 5. Compile y-- Engine and save it directly to the builds folder
            g++ -w -O3 -flto yrun.cpp qrcodegen.cpp -o builds/y_lang_arm -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -lncurses -lssl -lcrypto -lreplxx -rdynamic

      - name: Fix file permissions
        run: sudo chown -R $USER:$USER builds/

      - name: Commit and Push binary to Repository
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add builds/y_lang_arm
          
          git commit -m "Auto-compiled ARM binary (y_lang_arm)" || echo "No changes to commit"
          
          git push
